package hook

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func makeGitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".git", "hooks"), 0o755); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestInstallCreatesHooks(t *testing.T) {
	dir := makeGitRepo(t)
	installed, skipped, err := Install(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(installed) != 3 {
		t.Fatalf("want 3 hooks installed, got %d: %v", len(installed), installed)
	}
	if len(skipped) != 0 {
		t.Fatalf("unexpected skipped: %v", skipped)
	}
	for _, name := range HookNames {
		raw, err := os.ReadFile(filepath.Join(dir, ".git", "hooks", name))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(raw), "generated by aegis") {
			t.Fatalf("hook %s missing marker", name)
		}
	}
}

func TestInstallPreservesForeignHook(t *testing.T) {
	dir := makeGitRepo(t)
	foreign := "#!/bin/sh\n# a foreign hook\necho hi\n"
	if err := os.WriteFile(filepath.Join(dir, ".git", "hooks", "pre-commit"), []byte(foreign), 0o755); err != nil {
		t.Fatal(err)
	}
	installed, skipped, err := Install(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	if contains(installed, "pre-commit") {
		t.Fatal("should not overwrite foreign hook without --force")
	}
	if !contains(skipped, "pre-commit") {
		t.Fatal("foreign hook should appear in skipped list")
	}
	raw, _ := os.ReadFile(filepath.Join(dir, ".git", "hooks", "pre-commit"))
	if string(raw) != foreign {
		t.Fatal("foreign hook was modified")
	}
}

func TestUninstallOnlyRemovesOurs(t *testing.T) {
	dir := makeGitRepo(t)
	foreign := "#!/bin/sh\necho hi\n"
	if err := os.WriteFile(filepath.Join(dir, ".git", "hooks", "pre-commit"), []byte(foreign), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, _, err := Install(dir, false); err != nil {
		t.Fatal(err)
	}
	// manually install our marker for commit-msg
	body := "#!/usr/bin/env sh\n# generated by aegis\nexec aegis run --hook commit-msg\n"
	if err := os.WriteFile(filepath.Join(dir, ".git", "hooks", "commit-msg"), []byte(body), 0o755); err != nil {
		t.Fatal(err)
	}
	removed, err := Uninstall(dir)
	if err != nil {
		t.Fatal(err)
	}
	// pre-commit is foreign; should remain on disk untouched.
	raw, _ := os.ReadFile(filepath.Join(dir, ".git", "hooks", "pre-commit"))
	if string(raw) != foreign {
		t.Fatalf("uninstall must not touch foreign pre-commit; got %q", string(raw))
	}
	if !contains(removed, "commit-msg") {
		t.Fatalf("expected commit-msg in removed; got %v", removed)
	}
}

func contains(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}
