// Package hook installs and removes Aegis git hook stubs.
package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var HookNames = []string{"pre-commit", "commit-msg", "pre-push"}

// Template writes a tiny shell stub that dispatches to `aegis run --hook <name>`.
// We intentionally keep this shell-agnostic (POSIX sh) so it runs on macOS zsh,
// Linux bash, and minimal Alpine-like environments.
const hookTemplate = `#!/usr/bin/env sh
# .git/hooks/%[1]s — generated by aegis; do not edit manually.
exec aegis run --hook %[1]s "$@"
`

// Marker must match if we want to recognize our own hooks vs. pre-existing ones.
const hookMarker = "generated by aegis"

// Install writes (or refuses to overwrite) the hook files for each name.
// If force is true, existing files are replaced. Otherwise a non-Aegis hook
// is left untouched and the caller is warned.
func Install(repoRoot string, force bool) ([]string, []string, error) {
	hooksDir, err := resolveHooksDir(repoRoot)
	if err != nil {
		return nil, nil, err
	}
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return nil, nil, err
	}
	var installed, skipped []string
	for _, name := range HookNames {
		p := filepath.Join(hooksDir, name)
		body := fmt.Sprintf(hookTemplate, name)
		if existing, err := os.ReadFile(p); err == nil {
			if strings.Contains(string(existing), hookMarker) {
				// already ours; rewrite to pick up any template changes
			} else if !force {
				skipped = append(skipped, name)
				continue
			}
		}
		if err := os.WriteFile(p, []byte(body), 0o755); err != nil {
			return installed, skipped, err
		}
		installed = append(installed, name)
	}
	return installed, skipped, nil
}

// Uninstall removes only hooks that carry our marker; foreign hooks are preserved.
func Uninstall(repoRoot string) ([]string, error) {
	hooksDir, err := resolveHooksDir(repoRoot)
	if err != nil {
		return nil, err
	}
	var removed []string
	for _, name := range HookNames {
		p := filepath.Join(hooksDir, name)
		raw, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		if !strings.Contains(string(raw), hookMarker) {
			continue
		}
		if err := os.Remove(p); err != nil {
			return removed, err
		}
		removed = append(removed, name)
	}
	return removed, nil
}

// resolveHooksDir honors `git config core.hooksPath` but falls back to .git/hooks.
func resolveHooksDir(repoRoot string) (string, error) {
	gitDir := filepath.Join(repoRoot, ".git")
	st, err := os.Stat(gitDir)
	if err != nil {
		return "", fmt.Errorf("not a git repo: %s", repoRoot)
	}
	if st.IsDir() {
		return filepath.Join(gitDir, "hooks"), nil
	}
	// .git is a file (submodule/worktree case). Read gitdir line.
	raw, err := os.ReadFile(gitDir)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.HasPrefix(line, "gitdir:") {
			d := strings.TrimSpace(strings.TrimPrefix(line, "gitdir:"))
			if !filepath.IsAbs(d) {
				d = filepath.Join(repoRoot, d)
			}
			return filepath.Join(d, "hooks"), nil
		}
	}
	return "", fmt.Errorf("could not parse .git file at %s", gitDir)
}
